export const ActionTypes = {
    SET_POSTS: "SET_POSTS",
    SET_COMMENTS: "SET_COMMENTS",
    SET_ALBUMS: "SET ALBUMS",
    SET_PHOTOS: "SET_PHOTOS",

    SET_POSTCOUNT: "SET_POSTCOUNT",
    SET_COMMENTCOUNT: "SET_COMMENTCOUNT",
    SET_ALBUMCOUNT: "SET_ALBUMCOUNT",
    SET_PHOTOCOUNT: "SET_PHOTOCOUNT"
};
